c = input('Enter the city names - Delhi or Agra or Jaipur:')
if (c == 'Delhi'): print('Red Fort')
elif(c == 'Agra'): print('Taj Mahal')
elif(c == 'Jaipur'): print('Jal Mahal')
else: print('Enter another city name!')